ALTER TABLE address
ALTER COLUMN title SET NOT NULL,
ALTER COLUMN cep SET NOT NULL,
ALTER COLUMN residenceType SET NOT NULL,
ALTER COLUMN addressType SET NOT NULL,
ALTER COLUMN streetName SET NOT NULL,
ALTER COLUMN addressNumber SET NOT NULL,
ALTER COLUMN neighborhoods SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN state SET NOT NULL,
ALTER COLUMN country SET NOT NULL;