-- Migration para adicionar suporte a múltiplas cores e tags para produtos

-- Tabela de cores
CREATE TABLE colors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hex_code VARCHAR(7) NOT NULL,
    name VARCHAR(100),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_colors PRIMARY KEY (id),
    CONSTRAINT uc_colors_hex_code UNIQUE (hex_code)
);

-- Tabela de tags/características
CREATE TABLE tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id),
    CONSTRAINT uc_tags_name UNIQUE (name)
);

-- Tabela de relacionamento produto-cores (many-to-many)
CREATE TABLE product_colors (
    product_id INTEGER NOT NULL,
    color_id INTEGER NOT NULL,
    CONSTRAINT pk_product_colors PRIMARY KEY (product_id, color_id)
);

-- Tabela de relacionamento produto-tags (many-to-many)
CREATE TABLE product_tags (
    product_id INTEGER NOT NULL,
    tag_id INTEGER NOT NULL,
    CONSTRAINT pk_product_tags PRIMARY KEY (product_id, tag_id)
);

-- Foreign keys
ALTER TABLE product_colors
    ADD CONSTRAINT fk_product_colors_on_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE;

ALTER TABLE product_colors
    ADD CONSTRAINT fk_product_colors_on_color FOREIGN KEY (color_id) REFERENCES colors (id) ON DELETE CASCADE;

ALTER TABLE product_tags
    ADD CONSTRAINT fk_product_tags_on_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE;

ALTER TABLE product_tags
    ADD CONSTRAINT fk_product_tags_on_tag FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE;

-- Índices para melhor performance
CREATE INDEX idx_product_colors_product_id ON product_colors (product_id);
CREATE INDEX idx_product_colors_color_id ON product_colors (color_id);
CREATE INDEX idx_product_tags_product_id ON product_tags (product_id);
CREATE INDEX idx_product_tags_tag_id ON product_tags (tag_id);
CREATE INDEX idx_tags_name ON tags (name);


