CREATE TABLE address
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(255),
    cep           VARCHAR(255),
    residencetype VARCHAR(255),
    addresstype   VARCHAR(255),
    streetname    VARCHAR(255),
    addressnumber VARCHAR(255),
    neighborhoods VARCHAR(255),
    state         VARCHAR(255),
    city          VARCHAR(255),
    country       VARCHAR(255),
    observations  VARCHAR(255),
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE address_category
(
    id       BIGINT NOT NULL,
    category VARCHAR(255)
);

CREATE TABLE credit_card
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    card_flag   VARCHAR(255),
    card_number VARCHAR(255),
    card_name   VARCHAR(255),
    card_code   VARCHAR(255),
    main_card   BOOLEAN,
    customer_id BIGINT,
    CONSTRAINT pk_credit_card PRIMARY KEY (id)
);

CREATE TABLE credit_card_flags
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    flag_name VARCHAR(255),
    CONSTRAINT pk_credit_card_flags PRIMARY KEY (id)
);

CREATE TABLE customer
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR(255)                            NOT NULL,
    cpf        VARCHAR(11)                             NOT NULL,
    birthdate  VARCHAR(255),
    cellphone  VARCHAR(255),
    gender_id  BIGINT                                  NOT NULL,
    ranking    VARCHAR(255),
    user_id    BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE customer_address
(
    address_id  BIGINT NOT NULL,
    customer_id BIGINT,
    CONSTRAINT pk_customer_address PRIMARY KEY (address_id)
);

CREATE TABLE gender
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_gender PRIMARY KEY (id)
);

CREATE TABLE order_payments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    installments      INTEGER                                 NOT NULL,
    installment_value DECIMAL(10, 2)                          NOT NULL,
    method            VARCHAR(20)                             NOT NULL,
    credit_card_id    BIGINT,
    order_id          BIGINT                                  NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_order_payments PRIMARY KEY (id)
);

CREATE TABLE order_products
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    product_id INTEGER                                 NOT NULL,
    order_id   BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_order_products PRIMARY KEY (id)
);

CREATE TABLE order_shipments
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    delivery_time VARCHAR(255)                            NOT NULL,
    price         DOUBLE PRECISION                        NOT NULL,
    order_id      BIGINT                                  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_order_shipments PRIMARY KEY (id)
);

CREATE TABLE order_status
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_order_status PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id BIGINT                                  NOT NULL,
    address_id  BIGINT                                  NOT NULL,
    status_id   BIGINT                                  NOT NULL,
    type        VARCHAR(255)                            NOT NULL,
    total_price DOUBLE PRECISION                        NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE pricing_groups
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(100)                             NOT NULL,
    profit_margin DOUBLE PRECISION                         NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_pricing_groups PRIMARY KEY (id)
);

CREATE TABLE product_categories
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(100)                             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_product_categories PRIMARY KEY (id)
);

CREATE TABLE product_status_history
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id      INTEGER                                  NOT NULL,
    previous_status BOOLEAN                                  NOT NULL,
    new_status      BOOLEAN                                  NOT NULL,
    reason          TEXT,
    created_at      TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_product_status_history PRIMARY KEY (id)
);

CREATE TABLE products
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                             NOT NULL,
    description       TEXT,
    price             DECIMAL(10, 2)                           NOT NULL,
    sale_price        DECIMAL(10, 2)                           NOT NULL,
    type              VARCHAR(100)                             NOT NULL,
    color             VARCHAR(50),
    image             BYTEA,
    is_active         BOOLEAN                                  NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    category_id       INTEGER                                  NOT NULL,
    pricing_groups_id INTEGER                                  NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE stock
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity          INTEGER                                  NOT NULL,
    reserved_quantity INTEGER                                  NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    product_id        INTEGER                                  NOT NULL,
    CONSTRAINT pk_stock PRIMARY KEY (id)
);

CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email     VARCHAR(255),
    password  VARCHAR(255),
    role      SMALLINT,
    is_active VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE customer
    ADD CONSTRAINT uc_customer_cpf UNIQUE (cpf);

ALTER TABLE customer
    ADD CONSTRAINT uc_customer_user UNIQUE (user_id);

ALTER TABLE order_shipments
    ADD CONSTRAINT uc_order_shipments_order UNIQUE (order_id);

ALTER TABLE stock
    ADD CONSTRAINT uc_stock_product UNIQUE (product_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE credit_card
    ADD CONSTRAINT FK_CREDIT_CARD_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_GENDER FOREIGN KEY (gender_id) REFERENCES gender (id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_STATUS FOREIGN KEY (status_id) REFERENCES order_status (id);

ALTER TABLE order_payments
    ADD CONSTRAINT FK_ORDER_PAYMENTS_ON_CREDIT_CARD FOREIGN KEY (credit_card_id) REFERENCES credit_card (id);

ALTER TABLE order_payments
    ADD CONSTRAINT FK_ORDER_PAYMENTS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_products
    ADD CONSTRAINT FK_ORDER_PRODUCTS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_products
    ADD CONSTRAINT FK_ORDER_PRODUCTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE order_shipments
    ADD CONSTRAINT FK_ORDER_SHIPMENTS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES product_categories (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_PRICING_GROUPS FOREIGN KEY (pricing_groups_id) REFERENCES pricing_groups (id);

ALTER TABLE product_status_history
    ADD CONSTRAINT FK_PRODUCT_STATUS_HISTORY_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE stock
    ADD CONSTRAINT FK_STOCK_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE address_category
    ADD CONSTRAINT fk_address_category_on_address FOREIGN KEY (id) REFERENCES address (id);

ALTER TABLE customer_address
    ADD CONSTRAINT fk_cusadd_on_address FOREIGN KEY (address_id) REFERENCES address (id);

ALTER TABLE customer_address
    ADD CONSTRAINT fk_cusadd_on_customer FOREIGN KEY (customer_id) REFERENCES customer (id);