-- Tabela para armazenar traduções de tags (português -> inglês)
-- Isso permite cache de traduções e melhora performance
CREATE TABLE tag_translations
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tag_id     INTEGER                                   NOT NULL,
    language   VARCHAR(10)                               NOT NULL,
    translation VARCHAR(200)                             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_tag_translations PRIMARY KEY (id),
    CONSTRAINT uc_tag_translations_tag_language UNIQUE (tag_id, language)
);

ALTER TABLE tag_translations
    ADD CONSTRAINT fk_tag_translations_on_tag FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE;

CREATE INDEX idx_tag_translations_tag_id ON tag_translations (tag_id);
CREATE INDEX idx_tag_translations_language ON tag_translations (language);

