-- Criação da tabela shipping_options
CREATE TABLE shipping_options
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                             NOT NULL,
    delivery_time VARCHAR(255)                             NOT NULL,
    base_price    DOUBLE PRECISION                         NOT NULL,
    price_per_kg  DOUBLE PRECISION                         NOT NULL,
    min_weight_kg DOUBLE PRECISION                         NOT NULL,
    max_weight_kg DOUBLE PRECISION                         NOT NULL,
    is_active     BOOLEAN                                  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_shipping_options PRIMARY KEY (id),
    CONSTRAINT uc_shipping_options_name UNIQUE (name)
);

-- Inserção de opções de frete padrão
INSERT INTO shipping_options (name, delivery_time, base_price, price_per_kg, min_weight_kg, max_weight_kg, is_active, created_at, updated_at) VALUES
-- Frete Econômico: mais barato, entrega mais demorada
('Frete Econômico', '15 a 20 dias úteis', 15.00, 2.50, 0.0, 50.0, true, NOW(), NOW()),

-- Frete Padrão: equilíbrio entre preço e velocidade
('Frete Padrão', '10 a 15 dias úteis', 25.00, 3.50, 0.0, 100.0, true, NOW(), NOW()),

-- Frete Expresso: mais rápido, mais caro
('Frete Expresso', '5 a 8 dias úteis', 45.00, 5.00, 0.0, 200.0, true, NOW(), NOW()),

-- Frete Urgente: entrega rápida para produtos pesados
('Frete Urgente', '3 a 5 dias úteis', 80.00, 8.00, 0.0, 500.0, true, NOW(), NOW());

